### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by andreemidio** [lucasgomide/videos-pt.br-tecnologia#142]
Posso criar a lista de canais de comunidades de telegram ?

Creio que pode ser interessante, lá tem muitas pessoas para tirar dúvida.

**Comment by christyanbrayan** [comment]
@andreemidio você chegou a começar a criar?

**Comment by brunohhomem** [comment]
Oi, tem o link do canal?

**Comment by andreemidio** [comment]
@christyanbrayan, cheguei a criar, mas deu erro no merge, terei que fazer de novo, vou revisar a lista atual e o que eu souber adiciono lá

**Comment by lucasgomide** [comment]
@andreemidio Você ainda tem interesse em manter essa issue aberta? Se não, irei fecha-la.
