### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by giovannism20** [lucasgomide/videos-pt.br-tecnologia#161]
Sou uma pessoa pouco centrada quanto a plataforma do YouTube, com aquelas sugestões acabo perdendo muito tempo e as vezes só quero acompanhar o canal. Deixo também os cookies desativados e optei por usar apenas feed RSS. Gostaria de saber sobre a possibilidade de colocarmos link para o RSS dos canais.

**Comment by lucasgomide** [comment]
Olá @GiovanniSM20 Como anda esta feature? Seria muito interessante adicionar isso ao nosso code base

**Comment by GiovanniSM20** [comment]
Na verdade não é uma issue e sim colocar uma lista com o RSS dos canais para serem importados para os clientes.

**Comment by lucasgomide** [comment]
Você estava/esta trabalhando ainda nisso?

**Comment by GiovanniSM20** [comment]
Não

**Comment by lucasgomide** [comment]
O @developerfred estava trabalhando nisso, mas parece que não esta mais.
developerfred, vc pretende voltar a trabalhar nisso? Se não, eu posso continuar.
